# Generated by Django 2.1.7 on 2019-04-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoreview', '0002_restoinfo_resto_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restoinfo',
            name='resto_date',
        ),
    ]
