# Generated by Django 2.1.7 on 2019-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoreview', '0003_remove_restoinfo_resto_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoinfo',
            name='resto_detail',
            field=models.TextField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
