# Generated by Django 2.1.7 on 2019-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoreview', '0004_restoinfo_resto_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='restoinfo_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_test', models.CharField(max_length=200)),
            ],
        ),
    ]
